program: BalaApril05.o getdouble.o
	gcc BalaApril05.o getdouble.o -o program -lm

BalaApril05.o: BalaApril05.c getdouble.h
	gcc -c BalaApril05.c

getdouble.o: getdouble.c getdouble.h
	gcc -c getdouble.c
