program: BalaApril10.o getdouble.o
	gcc BalaApril10.o getdouble.o -o program -lm

BalaApril10.o: BalaApril10.c getdouble.h
	gcc -c BalaApril10.c

getdouble.o: getdouble.c getdouble.h
	gcc -c getdouble.c
